export default [
  {
    "Title":"The Shawshank Redemption",
    "Year":"1994",
    "Rated":"R",
    "Released":"14 Oct 1994",
    "Runtime":"2 h 22 min",
    "Genre":"Crime, Drama",
    "Director":"Frank Darabont",
    "Writer":"Stephen King, Frank Darabont",
    "Actors":"Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    "Plot":"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SX300.jpg",
    "imdbRating":"9.3",
    "imdbVotes":"1,078,045",
    "imdbID":"tt0111161",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=6hB3S9bIaco"
    }
  },
  {
    "Title":"Fight Club",
    "Year":"1999",
    "Rated":"R",
    "Released":"15 Oct 1999",
    "Runtime":"2 h 19 min",
    "Genre":"Drama",
    "Director":"David Fincher",
    "Writer":"Chuck Palahniuk, Jim Uhls",
    "Actors":"Brad Pitt, Edward Norton, Helena Bonham Carter, Meat Loaf",
    "Plot":"An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjIwNTYzMzE1M15BMl5BanBnXkFtZTcwOTE5Mzg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.8",
    "imdbVotes":"819,812",
    "imdbID":"tt0137523",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=SUXWAEX2jlg"
    }
  },
  {
    "Title":"Indiana Jones and the Last Crusade",
    "Year":"1989",
    "Rated":"E",
    "Released":"24 May 1989",
    "Runtime":"2 h 7 min",
    "Genre":"Action, Adventure",
    "Director":"Steven Spielberg",
    "Writer":"Jeffrey Boam, George Lucas",
    "Actors":"Harrison Ford, Sean Connery, Alison Doody, Denholm Elliott",
    "Plot":"When Dr. Henry Jones Sr. suddenly goes missing while pursuing the Holy Grail, eminent archaeologist Indiana Jones must follow in his father's footsteps and stop the Nazis.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQxMTUyODg2OF5BMl5BanBnXkFtZTcwNDM2MjAxNA@@._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"341,239",
    "imdbID":"tt0097576",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=WGpq-LDV6jU"
    }
  },
  {
    "Title":"Star Wars: Episode V - The Empire Strikes Back",
    "Year":"1980",
    "Rated":"PG",
    "Released":"21 May 1980",
    "Runtime":"2 h 7 min",
    "Genre":"Action, Adventure, Sci-Fi",
    "Director":"Irvin Kershner",
    "Writer":"Leigh Brackett, Lawrence Kasdan",
    "Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams",
    "Plot":"After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjE2MzQwMTgxN15BMl5BanBnXkFtZTcwMDQzNjk2OQ@@._V1_SX300.jpg",
    "imdbRating":"8.8",
    "imdbVotes":"522,846",
    "imdbID":"tt0080684",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=PkEKIw0FU6Y"
    }
  },
  {
    "Title":"The Lord of the Rings: The Fellowship of the Ring",
    "Year":"2001",
    "Rated":"PG-13",
    "Released":"19 Dec 2001",
    "Runtime":"2 h 58 min",
    "Genre":"Action, Adventure, Fantasy",
    "Director":"Peter Jackson",
    "Writer":"J.R.R. Tolkien, Fran Walsh",
    "Actors":"Elijah Wood, Ian McKellen, Orlando Bloom, Sean Bean",
    "Plot":"A meek hobbit of The Shire and eight companions set out on a journey to Mount Doom to destroy the One Ring and the dark lord Sauron.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNTEyMjAwMDU1OV5BMl5BanBnXkFtZTcwNDQyNTkxMw@@._V1_SX300.jpg",
    "imdbRating":"8.8",
    "imdbVotes":"798,909",
    "imdbID":"tt0120737",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=VIgkpEgCV-I"
    }
  },
  {
    "Title":"One Flew Over the Cuckoo's Nest",
    "Year":"1975",
    "Rated":"R",
    "Released":"21 Nov 1975",
    "Runtime":"2 h 13 min",
    "Genre":"Drama",
    "Director":"Milos Forman",
    "Writer":"Lawrence Hauben, Bo Goldman",
    "Actors":"Jack Nicholson, Louise Fletcher, Michael Berryman, Peter Brocco",
    "Plot":"Upon admittance to a mental institution, a brash rebel rallies the patients to take on the oppressive head nurse.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTk5OTA4NTc0NF5BMl5BanBnXkFtZTcwNzI5Mzg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.8",
    "imdbVotes":"451,957",
    "imdbID":"tt0073486",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=2WSyJgydTsA"
    }
  },
  {
    "Title":"Inception",
    "Year":"2010",
    "Rated":"PG-13",
    "Released":"16 Jul 2010",
    "Runtime":"2 h 28 min",
    "Genre":"Action, Adventure, Mystery, Sci-Fi, Thriller",
    "Director":"Christopher Nolan",
    "Writer":"Christopher Nolan",
    "Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Ken Watanabe",
    "Plot":"A skilled extractor is offered a chance to regain his old life as payment for a task considered to be impossible.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    "imdbRating":"8.8",
    "imdbVotes":"851,292",
    "imdbID":"tt1375666",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=66TuSJo4dZM"
    }
  },
  {
    "Title":"Goodfellas",
    "Year":"1990",
    "Rated":"R",
    "Released":"19 Sep 1990",
    "Runtime":"2 h 26 min",
    "Genre":"Biography, Crime, Drama, Thriller",
    "Director":"Martin Scorsese",
    "Writer":"Nicholas Pileggi, Nicholas Pileggi",
    "Actors":"Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco",
    "Plot":"Henry Hill and his friends work their way up through the mob hierarchy.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjU3MTQ4OTA0MV5BMl5BanBnXkFtZTYwNjAyMDg4._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"473,919",
    "imdbID":"tt0099685",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=qo5jJpHtI1Y"
    }
  },
  {
    "Title":"Star Wars",
    "Year":"1977",
    "Rated":"PG",
    "Released":"25 May 1977",
    "Runtime":"2 h 1 min",
    "Genre":"Action, Adventure, Fantasy, Sci-Fi",
    "Director":"George Lucas",
    "Writer":"George Lucas",
    "Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Alec Guinness",
    "Plot":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the universe from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTU4NTczODkwM15BMl5BanBnXkFtZTcwMzEyMTIyMw@@._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"588,148",
    "imdbID":"tt0076759",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=9gvqpFbRKtQ"
    }
  },
  {
    "Title":"Seven Samurai",
    "Year":"1954",
    "Rated":"Unrated",
    "Released":"19 Nov 1956",
    "Runtime":"2 h 38 min",
    "Genre":"Action, Drama",
    "Director":"Akira Kurosawa",
    "Writer":"Akira Kurosawa, Shinobu Hashimoto",
    "Actors":"Toshir\u00f4 Mifune, Takashi Shimura, Keiko Tsushima, Yukiko Shimazaki",
    "Plot":"A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNzg5Mzk5Nzc0NF5BMl5BanBnXkFtZTcwNjg3MDQzMQ@@._V1_SX300.jpg",
    "imdbRating":"8.8",
    "imdbVotes":"162,278",
    "imdbID":"tt0047478",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=xnRUHtSgJ9o"
    }
  },
  {
    "Title":"Forrest Gump",
    "Year":"1994",
    "Rated":"PG-13",
    "Released":"06 Jul 1994",
    "Runtime":"2 h 22 min",
    "Genre":"Drama, Romance",
    "Director":"Robert Zemeckis",
    "Writer":"Winston Groom, Eric Roth",
    "Actors":"Tom Hanks, Robin Wright, Gary Sinise, Sally Field",
    "Plot":"Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQwMTA5MzI1MF5BMl5BanBnXkFtZTcwMzY5Mzg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"722,459",
    "imdbID":"tt0109830",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=uPIEn0M8su0"
    }
  },
  {
    "Title":"The Matrix",
    "Year":"1999",
    "Rated":"R",
    "Released":"31 Mar 1999",
    "Runtime":"2 h 16 min",
    "Genre":"Action, Adventure, Sci-Fi",
    "Director":"Andy Wachowski, Lana Wachowski",
    "Writer":"Andy Wachowski, Lana Wachowski",
    "Actors":"Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
    "Plot":"A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjEzNjg1NTg2NV5BMl5BanBnXkFtZTYwNjY3MzQ5._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"779,661",
    "imdbID":"tt0133093",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=m8e-FF8MsqU"
    }
  },
  {
    "Title":"The Godfather",
    "Year":"1972",
    "Rated":"R",
    "Released":"24 Mar 1972",
    "Runtime":"2 h 55 min",
    "Genre":"Crime, Drama",
    "Director":"Francis Ford Coppola",
    "Writer":"Mario Puzo, Francis Ford Coppola",
    "Actors":"Marlon Brando, Al Pacino, James Caan, Diane Keaton",
    "Plot":"The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjEyMjcyNDI4MF5BMl5BanBnXkFtZTcwMDA5Mzg3OA@@._V1_SX300.jpg",
    "imdbRating":"9.2",
    "imdbVotes":"762,332",
    "imdbID":"tt0068646",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=sY1S34973zA"
    }
  },
  {
    "Title":"The Lord of the Rings: The Two Towers",
    "Year":"2002",
    "Rated":"PG-13",
    "Released":"18 Dec 2002",
    "Runtime":"2 h 59 min",
    "Genre":"Action, Adventure, Fantasy",
    "Director":"Peter Jackson",
    "Writer":"J.R.R. Tolkien, Fran Walsh",
    "Actors":"Elijah Wood, Ian McKellen, Viggo Mortensen, Orlando Bloom",
    "Plot":"While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTAyNDU0NjY4NTheQTJeQWpwZ15BbWU2MDk4MTY2Nw@@._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"689,276",
    "imdbID":"tt0167261",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=Wek5UClasY8"
    }
  },
  {
    "Title":"City of God",
    "Year":"2002",
    "Rated":"R",
    "Released":"N/A",
    "Runtime":"2 h 10 min",
    "Genre":"Crime, Drama",
    "Director":"Fernando Meirelles, K\u00e1tia Lund",
    "Writer":"Paulo Lins, Br\u00e1ulio Mantovani",
    "Actors":"Alexandre Rodrigues, Matheus Nachtergaele, Leandro Firmino, Phellipe Haagensen",
    "Plot":"Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"355,070",
    "imdbID":"tt0317248",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=ioUE_5wpg_E"
    }
  },
  {
    "Title":"Se7en",
    "Year":"1995",
    "Rated":"R",
    "Released":"22 Sep 1995",
    "Runtime":"2 h 7 min",
    "Genre":"Crime, Mystery, Thriller",
    "Director":"David Fincher",
    "Writer":"Andrew Kevin Walker",
    "Actors":"Morgan Freeman, Brad Pitt, Kevin Spacey, Andrew Kevin Walker",
    "Plot":"Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQwNTU3MTE4NF5BMl5BanBnXkFtZTcwOTgxNDM2Mg@@._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"632,133",
    "imdbID":"tt0114369",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=J4YV2_TcCoE"
    }
  },
  {
    "Title":"The Silence of the Lambs",
    "Year":"1991",
    "Rated":"R",
    "Released":"14 Feb 1991",
    "Runtime":"1 h 58 min",
    "Genre":"Crime, Drama, Thriller",
    "Director":"Jonathan Demme",
    "Writer":"Thomas Harris, Ted Tally",
    "Actors":"Jodie Foster, Anthony Hopkins, Lawrence A. Bonney, Kasi Lemmons",
    "Plot":"A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"531,335",
    "imdbID":"tt0102926",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=lQKs169Sl0I"
    }
  },
  {
    "Title":"Once Upon a Time in the West",
    "Year":"1968",
    "Rated":"M",
    "Released":"21 Dec 1968",
    "Runtime":"2 h 55 min",
    "Genre":"Adventure, Western",
    "Director":"Sergio Leone",
    "Writer":"Sergio Leone, Sergio Donati",
    "Actors":"Henry Fonda, Charles Bronson, Claudia Cardinale, Jason Robards",
    "Plot":"Epic story of a mysterious stranger with a harmonica who joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTgwMzU1MDEyMl5BMl5BanBnXkFtZTcwNDc5Mzg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"147,078",
    "imdbID":"tt0064116",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=MNGQ1hUyx-k"
    }
  },
  {
    "Title":"Casablanca",
    "Year":"1942",
    "Rated":"PG",
    "Released":"23 Jan 1943",
    "Runtime":"1 h 42 min",
    "Genre":"Drama, Romance, War",
    "Director":"Michael Curtiz",
    "Writer":"Julius J. Epstein, Philip G. Epstein",
    "Actors":"Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains",
    "Plot":"Set in unoccupied Africa during the early days of World War II: An American expatriate meets a former lover, with unforeseen complications.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTcwNDI5MjI1Ml5BMl5BanBnXkFtZTYwODE4NDI2._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"280,085",
    "imdbID":"tt0034583",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=TLU41jUnWM4"
    }
  },
  {
    "Title":"The Usual Suspects",
    "Year":"1995",
    "Rated":"R",
    "Released":"16 Aug 1995",
    "Runtime":"1 h 46 min",
    "Genre":"Crime, Mystery, Thriller",
    "Director":"Bryan Singer",
    "Writer":"Christopher McQuarrie",
    "Actors":"Kevin Spacey, Gabriel Byrne, Chazz Palminteri, Stephen Baldwin",
    "Plot":"A boat has been destroyed, criminals are dead, and the key to this mystery lies with the only survivor and his twisted, convoluted story beginning with five career crooks in a seemingly random police lineup.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMzI1MjI5MDQyOV5BMl5BanBnXkFtZTcwNzE4Mjg3NA@@._V1_SX300.jpg",
    "imdbRating":"8.7",
    "imdbVotes":"487,894",
    "imdbID":"tt0114814",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=9MjV4EwR7Mg"
    }
  },
  {
    "Title":"Raiders of the Lost Ark",
    "Year":"1981",
    "Rated":"PG",
    "Released":"12 Jun 1981",
    "Runtime":"1 h 55 min",
    "Genre":"Action, Adventure",
    "Director":"Steven Spielberg",
    "Writer":"Lawrence Kasdan, George Lucas",
    "Actors":"Harrison Ford, Karen Allen, Paul Freeman, John Rhys-Davies",
    "Plot":"Archeologist and adventurer Indiana Jones is hired by the US government to find the Ark of the Covenant before the Nazis.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"443,705",
    "imdbID":"tt0082971",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=0ZOcoxjeUYo"
    }
  },
  {
    "Title":"Rear Window",
    "Year":"1954",
    "Rated":"Approved",
    "Released":"29 Jan 1955",
    "Runtime":"1 h 52 min",
    "Genre":"Mystery, Thriller",
    "Director":"Alfred Hitchcock",
    "Writer":"John Michael Hayes, Cornell Woolrich",
    "Actors":"James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter",
    "Plot":"A wheelchair bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDUzMTY0NTE3NF5BMl5BanBnXkFtZTYwNDEyOTM2._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"215,144",
    "imdbID":"tt0047396",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=6kCcZCMYw38"
    }
  },
  {
    "Title":"It's a Wonderful Life",
    "Year":"1946",
    "Rated":"Approved",
    "Released":"07 Jan 1947",
    "Runtime":"2 h 10 min",
    "Genre":"Drama, Family, Fantasy",
    "Director":"Frank Capra",
    "Writer":"Frances Goodrich, Albert Hackett",
    "Actors":"James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell",
    "Plot":"An angel helps a compassionate but despairingly frustrated businessman by showing what life would have been like if he never existed.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTMzMzY5NDc4M15BMl5BanBnXkFtZTcwMzc4NjIxNw@@._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"181,144",
    "imdbID":"tt0038650",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=LJfZaT8ncYk"
    }
  },
  {
    "Title":"The Godfather: Part II",
    "Year":"1974",
    "Rated":"R",
    "Released":"20 Dec 1974",
    "Runtime":"3 h 20 min",
    "Genre":"Crime, Drama",
    "Director":"Francis Ford Coppola",
    "Writer":"Francis Ford Coppola, Mario Puzo",
    "Actors":"Al Pacino, Robert De Niro, Robert Duvall, Diane Keaton",
    "Plot":"The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDc2NTM3MzU1Nl5BMl5BanBnXkFtZTcwMTA5Mzg3OA@@._V1_SX300.jpg",
    "imdbRating":"9.0",
    "imdbVotes":"496,772",
    "imdbID":"tt0071562",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=qJr92K_hKl0"
    }
  },
  {
    "Title":"Psycho",
    "Year":"1960",
    "Rated":"R",
    "Released":"08 Sep 1960",
    "Runtime":"1 h 49 min",
    "Genre":"Horror, Mystery, Thriller",
    "Director":"Alfred Hitchcock",
    "Writer":"Joseph Stefano, Robert Bloch",
    "Actors":"Anthony Perkins, Janet Leigh, Vera Miles, John Gavin",
    "Plot":"A Phoenix secretary steals $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTgyNDIxNzQ4MF5BMl5BanBnXkFtZTYwMzkyNTQ2._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"273,991",
    "imdbID":"tt0054215",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=NG3-GlvKPcg"
    }
  },
  {
    "Title":"L\u00e9on: The Professional",
    "Year":"1994",
    "Rated":"Unrated",
    "Released":"18 Nov 1994",
    "Runtime":"1 h 50 min",
    "Genre":"Crime, Drama, Thriller",
    "Director":"Luc Besson",
    "Writer":"Luc Besson",
    "Actors":"Jean Reno, Gary Oldman, Natalie Portman, Danny Aiello",
    "Plot":"A professional assassin rescues a young girl whose parents were killed in a police raid.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTgzMzg4MDkwNF5BMl5BanBnXkFtZTcwODAwNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"463,013",
    "imdbID":"tt0110413",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=DcsirofJrlM"
    }
  },
  {
    "Title":"Sunset Blvd.",
    "Year":"1950",
    "Rated":"Not Rated",
    "Released":"25 Aug 1950",
    "Runtime":"1 h 50 min",
    "Genre":"Drama, Film-Noir",
    "Director":"Billy Wilder",
    "Writer":"Charles Brackett, Billy Wilder",
    "Actors":"William Holden, Gloria Swanson, Erich von Stroheim, Nancy Olson",
    "Plot":"A hack screenwriter writes a screenplay for a former silent-film star who has faded into Hollywood obscurity.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTk2OTQ5NDA4MV5BMl5BanBnXkFtZTcwNDIyNzE3OQ@@._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"95,968",
    "imdbID":"tt0043014",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=xzYqUpV_B-A"
    }
  },
  {
    "Title":"American History X",
    "Year":"1998",
    "Rated":"R",
    "Released":"12 Feb 1999",
    "Runtime":"1 h 59 min",
    "Genre":"Crime, Drama",
    "Director":"Tony Kaye",
    "Writer":"David McKenna",
    "Actors":"Edward Norton, Edward Furlong, Beverly D'Angelo, Jennifer Lien",
    "Plot":"A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjMzNDUwNTIyMF5BMl5BanBnXkFtZTcwNjMwNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"505,207",
    "imdbID":"tt0120586",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=UV0VEstvjMM"
    }
  },
  {
    "Title":"Apocalypse Now",
    "Year":"1979",
    "Rated":"R",
    "Released":"15 Aug 1979",
    "Runtime":"2 h 33 min",
    "Genre":"Drama, War",
    "Director":"Francis Ford Coppola",
    "Writer":"John Milius, Francis Ford Coppola",
    "Actors":"Martin Sheen, Marlon Brando, Robert Duvall, Frederic Forrest",
    "Plot":"During the U.S.-Viet Nam War, Captain Willard is sent on a dangerous mission into Cambodia to assassinate a renegade colonel who has set himself up as a god among a local tribe.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTcyMzQ5NDM4OV5BMl5BanBnXkFtZTcwODUwNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"311,517",
    "imdbID":"tt0078788",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=Tt0xxAMTp8M"
    }
  },
  {
    "Title":"Terminator 2: Judgment Day",
    "Year":"1991",
    "Rated":"R",
    "Released":"03 Jul 1991",
    "Runtime":"2 h 32 min",
    "Genre":"Action, Sci-Fi, Thriller",
    "Director":"James Cameron",
    "Writer":"James Cameron, William Wisher Jr.",
    "Actors":"Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick",
    "Plot":"The cyborg who once tried to kill Sarah Connor is dead, and another T-101 must now protect her teenage son, John Connor, from an even more powerful and advanced Terminator, the T-1000.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTg5NzUwMDU5NF5BMl5BanBnXkFtZTcwMjk2MDA4Mg@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"488,507",
    "imdbID":"tt0103064",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=eajuMYNYtuY"
    }
  },
  {
    "Title":"Saving Private Ryan",
    "Year":"1998",
    "Rated":"TV-MA",
    "Released":"24 Jul 1998",
    "Runtime":"2 h 49 min",
    "Genre":"Action, Drama, War",
    "Director":"Steven Spielberg",
    "Writer":"Robert Rodat",
    "Actors":"Tom Hanks, Matt Damon, Tom Sizemore, Edward Burns",
    "Plot":"Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNjczODkxNTAxN15BMl5BanBnXkFtZTcwMTcwNjUxMw@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"553,260",
    "imdbID":"tt0120815",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=zwhP5b4tD6g"
    }
  },
  {
    "Title":"Memento",
    "Year":"2000",
    "Rated":"R",
    "Released":"11 Oct 2000",
    "Runtime":"1 h 53 min",
    "Genre":"Mystery, Thriller",
    "Director":"Christopher Nolan",
    "Writer":"Christopher Nolan, Jonathan Nolan",
    "Actors":"Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior",
    "Plot":"A man, suffering from short-term memory loss, uses notes and tattoos to hunt for the man he thinks killed his wife.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTc4MjUxNDAwN15BMl5BanBnXkFtZTcwMDMwNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"562,835",
    "imdbID":"tt0209144",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=0vS0E9bBSL0"
    }
  },
  {
    "Title":"City Lights",
    "Year":"1931",
    "Rated":"G",
    "Released":"07 Mar 1931",
    "Runtime":"1 h 27 min",
    "Genre":"Comedy, Drama, Romance",
    "Director":"Charles Chaplin",
    "Writer":"Charles Chaplin",
    "Actors":"Charles Chaplin, Virginia Cherrill, Florence Lee, Harry Myers",
    "Plot":"The Tramp struggles to help a blind flower girl he has fallen in love with.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTc2NzYxMzY5MV5BMl5BanBnXkFtZTYwNzY5MTE5._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"63,396",
    "imdbID":"tt0021749",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=X_W1tOngo-w"
    }
  },
  {
    "Title":"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "Year":"1964",
    "Rated":"Approved",
    "Released":"29 Jan 1964",
    "Runtime":"1 h 35 min",
    "Genre":"Comedy, Sci-Fi, War",
    "Director":"Stanley Kubrick",
    "Writer":"Stanley Kubrick, Terry Southern",
    "Actors":"Peter Sellers, George C. Scott, Sterling Hayden, Keenan Wynn",
    "Plot":"An insane general starts a process to nuclear holocaust that a war room of politicians and generals frantically try to stop.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTU2ODM2NTkxNF5BMl5BanBnXkFtZTcwOTMwMzU3Mg@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"249,706",
    "imdbID":"tt0057012",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=71I4bdA7lDA"
    }
  },
  {
    "Title":"Pulp Fiction",
    "Year":"1994",
    "Rated":"R",
    "Released":"14 Oct 1994",
    "Runtime":"2 h 48 min",
    "Genre":"Crime, Drama, Thriller",
    "Director":"Quentin Tarantino",
    "Writer":"Quentin Tarantino, Roger Avary",
    "Actors":"John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis",
    "Plot":"The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjE0ODk2NjczOV5BMl5BanBnXkFtZTYwNDQ0NDg4._V1_SX300.jpg",
    "imdbRating":"9.0",
    "imdbVotes":"843,376",
    "imdbID":"tt0110912",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=s7EdQ4FqbhY"
    }
  },
  {
    "Title":"Alien",
    "Year":"1979",
    "Rated":"TV-14",
    "Released":"22 Jun 1979",
    "Runtime":"1 h 57 min",
    "Genre":"Horror, Sci-Fi",
    "Director":"Ridley Scott",
    "Writer":"Dan O'Bannon, Ronald Shusett",
    "Actors":"Sigourney Weaver, Tom Skerritt, John Hurt, Veronica Cartwright",
    "Plot":"The commercial vessel Nostromo receives a distress call from an unexplored planet. After searching for survivors, the crew heads home only to realize that a deadly bioform has joined them.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTk3NzkwMjA3OV5BMl5BanBnXkFtZTYwMTIwOTk2._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"366,499",
    "imdbID":"tt0078748",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=bEVY_lonKf4"
    }
  },
  {
    "Title":"Modern Times",
    "Year":"1936",
    "Rated":"Approved",
    "Released":"25 Feb 1936",
    "Runtime":"1 h 27 min",
    "Genre":"Comedy, Drama",
    "Director":"Charles Chaplin",
    "Writer":"Charles Chaplin",
    "Actors":"Charles Chaplin, Paulette Goddard, Henry Bergman, Tiny Sandford",
    "Plot":"The Tramp struggles to live in modern industrial society with the help of a young homeless woman.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjMwMDA5NzEwOF5BMl5BanBnXkFtZTcwMzgwNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"80,905",
    "imdbID":"tt0027977",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=Ekwbgtp1_Vg"
    }
  },
  {
    "Title":"Spirited Away",
    "Year":"2001",
    "Rated":"PG",
    "Released":"20 Jul 2001",
    "Runtime":"2 h 5 min",
    "Genre":"Animation, Adventure, Family, Fantasy",
    "Director":"Hayao Miyazaki",
    "Writer":"Hayao Miyazaki",
    "Actors":"Daveigh Chase, Suzanne Pleshette, Miyu Irino, Susan Egan",
    "Plot":"In the middle of her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and monsters; where humans are changed into animals; and a bathhouse for these creatures.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjYxMDcyMzIzNl5BMl5BanBnXkFtZTYwNDg2MDU3._V1_SX300.jpg",
    "imdbRating":"8.6",
    "imdbVotes":"249,265",
    "imdbID":"tt0245429",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=6az9wGfeSgM"
    }
  },
  {
    "Title":"North by Northwest",
    "Year":"1959",
    "Rated":"Approved",
    "Released":"26 Sep 1959",
    "Runtime":"2 h 16 min",
    "Genre":"Action, Adventure, Crime, Mystery, Thriller",
    "Director":"Alfred Hitchcock",
    "Writer":"Ernest Lehman",
    "Actors":"Cary Grant, Eva Marie Saint, James Mason, Jessie Royce Landis",
    "Plot":"A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies, and is pursued across the country while he looks for a way to survive.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTc1MjczNTgxM15BMl5BanBnXkFtZTcwOTYwNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"156,431",
    "imdbID":"tt0053125",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=HRfmTpmIUwo"
    }
  },
  {
    "Title":"Back to the Future",
    "Year":"1985",
    "Rated":"PG",
    "Released":"03 Jul 1985",
    "Runtime":"1 h 56 min",
    "Genre":"Adventure, Comedy, Sci-Fi",
    "Director":"Robert Zemeckis",
    "Writer":"Robert Zemeckis, Bob Gale",
    "Actors":"Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover",
    "Plot":"A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend, Dr. Emmett Brown, and must make sure his high-school-age parents unite in order to save his own existence.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4OTQ1OTMwN15BMl5BanBnXkFtZTcwOTIwMzM3MQ@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"437,347",
    "imdbID":"tt0088763",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=yosuvf7Unmg"
    }
  },
  {
    "Title":"Life Is Beautiful",
    "Year":"1997",
    "Rated":"PG-13",
    "Released":"12 Feb 1999",
    "Runtime":"1 h 56 min",
    "Genre":"Comedy, Drama, Romance, War",
    "Director":"Roberto Benigni",
    "Writer":"Vincenzo Cerami, Roberto Benigni",
    "Actors":"Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini, Giustino Durano",
    "Plot":"A Jewish man has a wonderful romance with the help of his humour, but must use that same quality to protect his son in a Nazi death camp.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTM3NDg0OTkxOV5BMl5BanBnXkFtZTcwMTk2NzIyMQ@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"239,414",
    "imdbID":"tt0118799",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=16RZHqCIy9M"
    }
  },
  {
    "Title":"The Shining",
    "Year":"1980",
    "Rated":"R",
    "Released":"23 May 1980",
    "Runtime":"2 h 22 min",
    "Genre":"Horror, Mystery",
    "Director":"Stanley Kubrick",
    "Writer":"Stephen King, Stanley Kubrick",
    "Actors":"Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers",
    "Plot":"A family heads to an isolated hotel for the winter where an evil and spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BODMxMjE3NTA4Ml5BMl5BanBnXkFtZTgwNDc0NTIxMDE@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"382,542",
    "imdbID":"tt0081505",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=5Cb3ik6zP2I"
    }
  },
  {
    "Title":"The Pianist",
    "Year":"2002",
    "Rated":"R",
    "Released":"28 Mar 2003",
    "Runtime":"2 h 30 min",
    "Genre":"Biography, Drama, History, War",
    "Director":"Roman Polanski",
    "Writer":"Ronald Harwood, Wladyslaw Szpilman",
    "Actors":"Adrien Brody, Thomas Kretschmann, Frank Finlay, Emilia Fox",
    "Plot":"A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTc4OTkyOTA3OF5BMl5BanBnXkFtZTYwMDIxNjk5._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"299,214",
    "imdbID":"tt0253474",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=u_jE7-6Uv7E"
    }
  },
  {
    "Title":"Citizen Kane",
    "Year":"1941",
    "Rated":"Approved",
    "Released":"05 Sep 1941",
    "Runtime":"1 h 59 min",
    "Genre":"Drama, Mystery",
    "Director":"Orson Welles",
    "Writer":"Herman J. Mankiewicz, Orson Welles",
    "Actors":"Orson Welles, Joseph Cotten, Dorothy Comingore, Agnes Moorehead",
    "Plot":"Following the death of a publishing tycoon, news reporters scramble to discover the meaning of his final utterance.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ2Mjc1MDQwMl5BMl5BanBnXkFtZTcwNzUyOTUyMg@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"217,872",
    "imdbID":"tt0033467",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=zyv19bg0scg"
    }
  },
  {
    "Title":"The Departed",
    "Year":"2006",
    "Rated":"R",
    "Released":"06 Oct 2006",
    "Runtime":"2 h 31 min",
    "Genre":"Crime, Drama, Thriller",
    "Director":"Martin Scorsese",
    "Writer":"William Monahan, Alan Mak",
    "Actors":"Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg",
    "Plot":"An undercover state cop who has infiltrated an Irish gang and a mole in the police force working for the same mob race to track down and identify each other before being exposed to the enemy, after both sides realize their outfit has a rat.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"550,166",
    "imdbID":"tt0407887",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=SGWvwjZ0eDc"
    }
  },
  {
    "Title":"The Good, the Bad and the Ugly",
    "Year":"1966",
    "Rated":"M",
    "Released":"29 Dec 1967",
    "Runtime":"2 h 41 min",
    "Genre":"Adventure, Western",
    "Director":"Sergio Leone",
    "Writer":"Luciano Vincenzoni, Sergio Leone",
    "Actors":"Clint Eastwood, Eli Wallach, Lee Van Cleef, Aldo Giuffr\u00e8",
    "Plot":"A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjIxNjYwNDMzMl5BMl5BanBnXkFtZTcwODA5Mzg3OA@@._V1_SX300.jpg",
    "imdbRating":"9.0",
    "imdbVotes":"325,579",
    "imdbID":"tt0060196",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=JdkSuurdbDA"
    }
  },
  {
    "Title":"M",
    "Year":"1931",
    "Rated":"Not Rated",
    "Released":"31 Aug 1931",
    "Runtime":"1 h 39 min",
    "Genre":"Crime, Drama, Thriller",
    "Director":"Fritz Lang",
    "Writer":"Thea von Harbou, Fritz Lang",
    "Actors":"Peter Lorre, Ellen Widmann, Inge Landgut, Otto Wernicke",
    "Plot":"When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTIwNDU4OTI2MF5BMl5BanBnXkFtZTcwNzI5MjcyMQ@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"69,261",
    "imdbID":"tt0022100",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=cIj3Bk0bhL8"
    }
  },
  {
    "Title":"Paths of Glory",
    "Year":"1957",
    "Rated":"Approved",
    "Released":"25 Oct 1957",
    "Runtime":"1 h 28 min",
    "Genre":"Drama, War",
    "Director":"Stanley Kubrick",
    "Writer":"Stanley Kubrick, Calder Willingham",
    "Actors":"Kirk Douglas, Ralph Meeker, Adolphe Menjou, George Macready",
    "Plot":"When soldiers in World War I refuse to continue with an impossible attack, their superior officers decide to make an example of them.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTUxNTcxMjI5NV5BMl5BanBnXkFtZTcwNTcyNjI3Mw@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"79,379",
    "imdbID":"tt0050825",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=nmDA60X-f_A"
    }
  },
  {
    "Title":"Vertigo",
    "Year":"1958",
    "Rated":"Approved",
    "Released":"21 Jul 1958",
    "Runtime":"2 h 9 min",
    "Genre":"Mystery, Romance, Thriller",
    "Director":"Alfred Hitchcock",
    "Writer":"Alec Coppel, Samuel A. Taylor",
    "Actors":"James Stewart, Kim Novak, Barbara Bel Geddes, Tom Helmore",
    "Plot":"A retired San Francisco detective suffering from acrophobia investigates the strange activities of an old friend's wife, all the while becoming dangerously obsessed with her.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNzY0NzQyNzQzOF5BMl5BanBnXkFtZTcwMTgwNTk4OQ@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"163,850",
    "imdbID":"tt0052357",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=Z5jvQwwHQNY"
    }
  },
  {
    "Title":"Django Unchained",
    "Year":"2012",
    "Rated":"R",
    "Released":"25 Dec 2012",
    "Runtime":"2 h 45 min",
    "Genre":"Adventure, Drama, Western",
    "Director":"Quentin Tarantino",
    "Writer":"Quentin Tarantino",
    "Actors":"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington",
    "Plot":"With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"459,782",
    "imdbID":"tt1853728",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=eUdM9vrCbow"
    }
  },
  {
    "Title":"Double Indemnity",
    "Year":"1944",
    "Rated":"Approved",
    "Released":"24 Apr 1944",
    "Runtime":"1 h 47 min",
    "Genre":"Crime, Drama, Film-Noir, Thriller",
    "Director":"Billy Wilder",
    "Writer":"Billy Wilder, Raymond Chandler",
    "Actors":"Fred MacMurray, Barbara Stanwyck, Edward G. Robinson, Byron Barr",
    "Plot":"An insurance rep lets himself be talked into a murder/insurance fraud scheme that arouses an insurance investigator's suspicions.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTUyNzM2NzM2NV5BMl5BanBnXkFtZTcwNzYxNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"66,811",
    "imdbID":"tt0036775",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=yKrrAa2o9Eg"
    }
  },
  {
    "Title":"The Dark Knight Rises",
    "Year":"2012",
    "Rated":"PG-13",
    "Released":"20 Jul 2012",
    "Runtime":"2 h 45 min",
    "Genre":"Action, Crime, Thriller",
    "Director":"Christopher Nolan",
    "Writer":"Jonathan Nolan, Christopher Nolan",
    "Actors":"Christian Bale, Tom Hardy, Anne Hathaway, Gary Oldman",
    "Plot":"Eight years on, a new evil rises from where the Batman and Commissioner Gordon tried to bury it, causing the Batman to resurface and fight to protect Gotham City... the very city which brands him an enemy.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"687,392",
    "imdbID":"tt1345836",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=g8evyE9TuYk"
    }
  },
  {
    "Title":"Aliens",
    "Year":"1986",
    "Rated":"R",
    "Released":"18 Jul 1986",
    "Runtime":"2 h 34 min",
    "Genre":"Action, Adventure, Sci-Fi, Thriller",
    "Director":"James Cameron",
    "Writer":"James Cameron, David Giler",
    "Actors":"Sigourney Weaver, Michael Biehn, Carrie Henn, Paul Reiser",
    "Plot":"The planet from 'Alien' has been colonized, but contact is lost. This time, the rescue team has impressive firepower, but will it be enough?",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTYzNzU5MzQ4OV5BMl5BanBnXkFtZTcwMDcxNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"331,518",
    "imdbID":"tt0090605",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"rtsp://r8---sn-4g57kue6.c.youtube.com/CiILENy73wIaGQkhIxqFmZCkXBMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp"
    }
  },
  {
    "Title":"Taxi Driver",
    "Year":"1976",
    "Rated":"R",
    "Released":"08 Feb 1976",
    "Runtime":"1 h 53 min",
    "Genre":"Crime, Drama",
    "Director":"Martin Scorsese",
    "Writer":"Paul Schrader",
    "Actors":"Robert De Niro, Jodie Foster, Cybill Shepherd, Albert Brooks",
    "Plot":"A mentally unstable Viet Nam war veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action, attempting to save a preadolescent prostitute in the process.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ1Nzg3MDQwN15BMl5BanBnXkFtZTcwNDE2NDU2MQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"323,426",
    "imdbID":"tt0075314",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=sLpMx8_TYOo"
    }
  },
  {
    "Title":"American Beauty",
    "Year":"1999",
    "Rated":"R",
    "Released":"01 Oct 1999",
    "Runtime":"2 h 2 min",
    "Genre":"Drama",
    "Director":"Sam Mendes",
    "Writer":"Alan Ball",
    "Actors":"Kevin Spacey, Annette Bening, Thora Birch, Wes Bentley",
    "Plot":"Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation for his daughter's attractive friend.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BOTU1MzExMDg3N15BMl5BanBnXkFtZTcwODExNDg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"563,756",
    "imdbID":"tt0169547",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=3ycmmJ6rxA8"
    }
  },
  {
    "Title":"The Green Mile",
    "Year":"1999",
    "Rated":"R",
    "Released":"10 Dec 1999",
    "Runtime":"3 h 9 min",
    "Genre":"Crime, Drama, Fantasy, Mystery",
    "Director":"Frank Darabont",
    "Writer":"Stephen King, Frank Darabont",
    "Actors":"Tom Hanks, Michael Clarke Duncan, David Morse, Bonnie Hunt",
    "Plot":"The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"456,170",
    "imdbID":"tt0120689",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=ctRK-4Vt7dA"
    }
  },
  {
    "Title":"The Dark Knight",
    "Year":"2008",
    "Rated":"PG-13",
    "Released":"18 Jul 2008",
    "Runtime":"2 h 32 min",
    "Genre":"Action, Crime, Drama, Thriller",
    "Director":"Christopher Nolan",
    "Writer":"Jonathan Nolan, Christopher Nolan",
    "Actors":"Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    "Plot":"When Batman, Gordon and Harvey Dent launch an assault on the mob, they let the clown out of the box, the Joker, bent on turning Gotham on itself and bringing any heroes down to his level.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    "imdbRating":"9.0",
    "imdbVotes":"1,050,810",
    "imdbID":"tt0468569",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=yQ5U8suTUw0"
    }
  },
  {
    "Title":"Gladiator",
    "Year":"2000",
    "Rated":"R",
    "Released":"05 May 2000",
    "Runtime":"2 h 35 min",
    "Genre":"Action, Adventure, Drama",
    "Director":"Ridley Scott",
    "Writer":"David Franzoni, David Franzoni",
    "Actors":"Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed",
    "Plot":"When a Roman general is betrayed and his family murdered by an emperor's corrupt son, he comes to Rome as a gladiator to seek revenge.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNTQ2NzI0ODc5MV5BMl5BanBnXkFtZTcwMTA0MTk3OA@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"610,144",
    "imdbID":"tt0172495",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=ol67qo3WhJk"
    }
  },
  {
    "Title":"The Intouchables",
    "Year":"2011",
    "Rated":"R",
    "Released":"02 Nov 2011",
    "Runtime":"1 h 52 min",
    "Genre":"Biography, Comedy, Drama",
    "Director":"Olivier Nakache, Eric Toledano",
    "Writer":"Olivier Nakache, Eric Toledano",
    "Actors":"Fran\u00e7ois Cluzet, Omar Sy, Anne Le Ny, Audrey Fleurot",
    "Plot":"After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caretaker.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"232,430",
    "imdbID":"tt1675434",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=34WIbmXkewU"
    }
  },
  {
    "Title":"WALL\u00b7E",
    "Year":"2008",
    "Rated":"G",
    "Released":"27 Jun 2008",
    "Runtime":"1 h 38 min",
    "Genre":"Animation, Adventure, Family, Romance, Sci-Fi",
    "Director":"Andrew Stanton",
    "Writer":"Andrew Stanton, Pete Docter",
    "Actors":"Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard",
    "Plot":"In the distant future, a small waste collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTczOTA3MzY2N15BMl5BanBnXkFtZTcwOTYwNjE2MQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"433,972",
    "imdbID":"tt0910970",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=alIq_wG9FNk"
    }
  },
  {
    "Title":"The Lives of Others",
    "Year":"2006",
    "Rated":"R",
    "Released":"23 Mar 2006",
    "Runtime":"2 h 17 min",
    "Genre":"Drama, Thriller",
    "Director":"Florian Henckel von Donnersmarck",
    "Writer":"Florian Henckel von Donnersmarck",
    "Actors":"Ulrich M\u00fche, Martina Gedeck, Sebastian Koch, Ulrich Tukur",
    "Plot":"In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDUzNjYwNDYyNl5BMl5BanBnXkFtZTcwNjU3ODQ0MQ@@._V1_SX300.jpg",
    "imdbRating":"8.5",
    "imdbVotes":"171,007",
    "imdbID":"tt0405094",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=FppW5ml4vdw"
    }
  },
  {
    "Title":"Toy Story 3",
    "Year":"2010",
    "Rated":"G",
    "Released":"18 Jun 2010",
    "Runtime":"1 h 43 min",
    "Genre":"Animation, Adventure, Comedy, Family, Fantasy",
    "Director":"Lee Unkrich",
    "Writer":"John Lasseter, Andrew Stanton",
    "Actors":"Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty",
    "Plot":"The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"324,092",
    "imdbID":"tt0435761",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=JcpWXaA2qeg"
    }
  },
  {
    "Title":"The Great Dictator",
    "Year":"1940",
    "Rated":"Approved",
    "Released":"07 Mar 1941",
    "Runtime":"2 h 5 min",
    "Genre":"Comedy, Drama, War",
    "Director":"Charles Chaplin",
    "Writer":"Charles Chaplin",
    "Actors":"Charles Chaplin, Paulette Goddard, Jack Oakie, Reginald Gardiner",
    "Plot":"Dictator Adenoid Hynkel has a doppelganger, a poor but kind Jewish barber living in the slums, who one day is mistaken for Hynkel.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQyNTgyNTQ3N15BMl5BanBnXkFtZTcwMzgyMDYyMQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"79,002",
    "imdbID":"tt0032553",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=zroWIN-lS8E"
    }
  },
  {
    "Title":"The Prestige",
    "Year":"2006",
    "Rated":"PG-13",
    "Released":"20 Oct 2006",
    "Runtime":"2 h 10 min",
    "Genre":"Drama, Mystery, Thriller",
    "Director":"Christopher Nolan",
    "Writer":"Jonathan Nolan, Christopher Nolan",
    "Actors":"Christian Bale, Hugh Jackman, Scarlett Johansson, Michael Caine",
    "Plot":"The rivalry between two magicians becomes more exacerbated by their attempt to perform the ultimate illusion.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"502,556",
    "imdbID":"tt0482571",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=o4gHCmTQDVI"
    }
  },
  {
    "Title":"A Clockwork Orange",
    "Year":"1971",
    "Rated":"X",
    "Released":"02 Feb 1972",
    "Runtime":"2 h 16 min",
    "Genre":"Crime, Drama, Sci-Fi",
    "Director":"Stanley Kubrick",
    "Writer":"Stanley Kubrick, Anthony Burgess",
    "Actors":"Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke",
    "Plot":"In future Britain, charismatic delinquent Alex DeLarge is jailed and volunteers for an experimental aversion therapy developed by the government in an effort to solve society's crime problem... but not all goes to plan.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"362,302",
    "imdbID":"tt0066921",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=G7fO3bzPeBQ"
    }
  },
  {
    "Title":"Lawrence of Arabia",
    "Year":"1962",
    "Rated":"PG",
    "Released":"30 Jan 1963",
    "Runtime":"3 h 47 min",
    "Genre":"Adventure, Biography, Drama, History, War",
    "Director":"David Lean",
    "Writer":"T.E. Lawrence, Robert Bolt",
    "Actors":"Peter O'Toole, Alec Guinness, Anthony Quinn, Jack Hawkins",
    "Plot":"A flamboyant and controversial British military figure and his conflicted loyalties during his World War I service in Arabia.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMzAwMjM4NzA2OV5BMl5BanBnXkFtZTcwMDI0NzAwMQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"131,669",
    "imdbID":"tt0056172",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=a3tuBFHuYV4"
    }
  },
  {
    "Title":"Am\u00e9lie",
    "Year":"2001",
    "Rated":"R",
    "Released":"25 Apr 2001",
    "Runtime":"2 h 2 min",
    "Genre":"Comedy, Romance",
    "Director":"Jean-Pierre Jeunet",
    "Writer":"Guillaume Laurant, Jean-Pierre Jeunet",
    "Actors":"Audrey Tautou, Mathieu Kassovitz, Rufus, Lorella Cravotta",
    "Plot":"Amelie, an innocent and naive girl in Paris, with her own sense of justice, decides to help those around her and along the way, discovers love.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTUwNzkwMTk5Nl5BMl5BanBnXkFtZTYwMDAzMDI5._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"353,101",
    "imdbID":"tt0211915",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=sECzJY07oK4"
    }
  },
  {
    "Title":"12 Angry Men",
    "Year":"1957",
    "Rated":"Approved",
    "Released":"01 Apr 1957",
    "Runtime":"1 h 36 min",
    "Genre":"Drama",
    "Director":"Sidney Lumet",
    "Writer":"Reginald Rose",
    "Actors":"Henry Fonda, Lee J. Cobb, Martin Balsam, John Fiedler",
    "Plot":"A dissenting juror in a murder trial slowly manages to convince the others that the case is not as obviously clear as it seemed in court.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SX300.jpg",
    "imdbRating":"8.9",
    "imdbVotes":"266,350",
    "imdbID":"tt0050083",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=A7CBKT0PWFA"
    }
  },
  {
    "Title":"To Kill a Mockingbird",
    "Year":"1962",
    "Rated":"Approved",
    "Released":"16 Mar 1963",
    "Runtime":"2 h 9 min",
    "Genre":"Crime, Drama, Mystery",
    "Director":"Robert Mulligan",
    "Writer":"Harper Lee, Horton Foote",
    "Actors":"Gregory Peck, John Megna, Frank Overton, Rosemary Murphy",
    "Plot":"Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his kids against prejudice.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjA4MzI1NDY2Nl5BMl5BanBnXkFtZTcwMTcyODc5Mw@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"143,692",
    "imdbID":"tt0056592",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=KR7loA_oziY"
    }
  },
  {
    "Title":"Reservoir Dogs",
    "Year":"1992",
    "Rated":"R",
    "Released":"23 Oct 1992",
    "Runtime":"1 h 39 min",
    "Genre":"Crime, Thriller",
    "Director":"Quentin Tarantino",
    "Writer":"Quentin Tarantino, Roger Avary",
    "Actors":"Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn",
    "Plot":"After a simple jewelery heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQxMTAwMDQ3Nl5BMl5BanBnXkFtZTcwODMwNTgzMQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"419,737",
    "imdbID":"tt0105236",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=QvoKT481EmU"
    }
  },
  {
    "Title":"Das Boot",
    "Year":"1981",
    "Rated":"R",
    "Released":"10 Feb 1982",
    "Runtime":"2 h 29 min",
    "Genre":"Action, Adventure, Drama, History, War",
    "Director":"Wolfgang Petersen",
    "Writer":"Wolfgang Petersen, Lothar G. Buchheim",
    "Actors":"J\u00fcrgen Prochnow, Herbert Gr\u00f6nemeyer, Klaus Wennemann, Hubertus Bengsch",
    "Plot":"The claustrophobic world of a WWII German U-boat; boredom, filth, and sheer terror.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjE5Mzk5OTQ0Nl5BMl5BanBnXkFtZTYwNzUwMTQ5._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"119,251",
    "imdbID":"tt0082096",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=7pzKyeIex2Y"
    }
  },
  {
    "Title":"The Lion King",
    "Year":"1994",
    "Rated":"G",
    "Released":"24 Jun 1994",
    "Runtime":"1 h 29 min",
    "Genre":"Animation, Adventure, Drama, Family, Musical",
    "Director":"Roger Allers, Rob Minkoff",
    "Writer":"Irene Mecchi, Jonathan Roberts",
    "Actors":"Matthew Broderick, Jeremy Irons, James Earl Jones, Whoopi Goldberg",
    "Plot":"Tricked into thinking he killed his father, a guilt ridden lion cub flees into exile and abandons his identity as the future King.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjEyMzgwNTUzMl5BMl5BanBnXkFtZTcwNTMxMzM3Ng@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"368,630",
    "imdbID":"tt0110357",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=4sj1MT05lAA"
    }
  },
  {
    "Title":"Cinema Paradiso",
    "Year":"1988",
    "Rated":"PG",
    "Released":"23 Feb 1990",
    "Runtime":"2 h 35 min",
    "Genre":"Drama",
    "Director":"Giuseppe Tornatore",
    "Writer":"Giuseppe Tornatore, Giuseppe Tornatore",
    "Actors":"Philippe Noiret, Enzo Cannavale, Antonella Attili, Isa Danieli",
    "Plot":"A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDMwNDk3NDQ0Nl5BMl5BanBnXkFtZTcwNjEwMjI2MQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"93,606",
    "imdbID":"tt0095765",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=C2-GX0Tltgw"
    }
  },
  {
    "Title":"Star Wars: Episode VI - Return of the Jedi",
    "Year":"1983",
    "Rated":"PG",
    "Released":"25 May 1983",
    "Runtime":"2 h 14 min",
    "Genre":"Action, Adventure, Fantasy, Sci-Fi",
    "Director":"Richard Marquand",
    "Writer":"Lawrence Kasdan, George Lucas",
    "Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams",
    "Plot":"After rescuing Han Solo from the palace of Jabba the Hutt, the Rebels attempt to destroy the Second Death Star, while Luke Skywalker tries to bring his father back to the Light Side of the Force.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjE5MTM3ODU5MV5BMl5BanBnXkFtZTcwOTYzNjk2OQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"413,603",
    "imdbID":"tt0086190",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=OvUh9_GFXA0"
    }
  },
  {
    "Title":"The Treasure of the Sierra Madre",
    "Year":"1948",
    "Rated":"Approved",
    "Released":"24 Jan 1948",
    "Runtime":"2 h 6 min",
    "Genre":"Action, Adventure, Drama, Western",
    "Director":"John Huston",
    "Writer":"John Huston, B. Traven",
    "Actors":"Humphrey Bogart, Walter Huston, Tim Holt, Bruce Bennett",
    "Plot":"Fred Dobbs and Bob Curtin, two Americans searching for work in Mexico, convince an old prospector to help them mine for gold in the Sierra Madre Mountains.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjEyMjU0ODM3OV5BMl5BanBnXkFtZTcwNDkyMTUyMg@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"55,638",
    "imdbID":"tt0040897",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=vGpvO8JabEc"
    }
  },
  {
    "Title":"The Third Man",
    "Year":"1949",
    "Rated":"Approved",
    "Released":"31 Aug 1949",
    "Runtime":"1 h 33 min",
    "Genre":"Film-Noir, Mystery, Thriller",
    "Director":"Carol Reed",
    "Writer":"Graham Greene, Graham Greene",
    "Actors":"Orson Welles, Joseph Cotten, Alida Valli, Trevor Howard",
    "Plot":"Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, black-market opportunist Harry Lime.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTYzOTAxNzAyNl5BMl5BanBnXkFtZTcwNjc0OTM0MQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"81,528",
    "imdbID":"tt0041959",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=HjMDg1Z9_gA"
    }
  },
  {
    "Title":"Once Upon a Time in America",
    "Year":"1984",
    "Rated":"R",
    "Released":"23 May 1984",
    "Runtime":"2 h 19 min",
    "Genre":"Crime, Drama",
    "Director":"Sergio Leone",
    "Writer":"Harry Grey, Leonardo Benvenuti",
    "Actors":"Robert De Niro, James Woods, Elizabeth McGovern, Joe Pesci",
    "Plot":"A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDMwMDcyODkzOV5BMl5BanBnXkFtZTcwNTQ1Njg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"148,708",
    "imdbID":"tt0087843",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=mzhX2PD6Srw"
    }
  },
  {
    "Title":"Requiem for a Dream",
    "Year":"2000",
    "Rated":"Unrated",
    "Released":"27 Oct 2000",
    "Runtime":"1 h 42 min",
    "Genre":"Drama",
    "Director":"Darren Aronofsky",
    "Writer":"Hubert Selby Jr., Hubert Selby Jr.",
    "Actors":"Ellen Burstyn, Jared Leto, Jennifer Connelly, Marlon Wayans",
    "Plot":"The drug-induced utopias of four Coney Island individuals are shattered when their addictions become stronger.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMzM2OTYwMTY4Nl5BMl5BanBnXkFtZTcwMjU1Njg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"384,686",
    "imdbID":"tt0180093",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=jzk-lmU4KZ4"
    }
  },
  {
    "Title":"Schindler's List",
    "Year":"1993",
    "Rated":"R",
    "Released":"15 Dec 1993",
    "Runtime":"3 h 15 min",
    "Genre":"Biography, Drama, History, War",
    "Director":"Steven Spielberg",
    "Writer":"Thomas Keneally, Steven Zaillian",
    "Actors":"Liam Neeson, Ralph Fiennes, Ben Kingsley, Caroline Goodall",
    "Plot":"In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMzMwMTM4MDU2N15BMl5BanBnXkFtZTgwMzQ0MjMxMDE@._V1_SX300.jpg",
    "imdbRating":"8.9",
    "imdbVotes":"553,804",
    "imdbID":"tt0108052",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=dwfIf1WMhgc"
    }
  },
  {
    "Title":"Eternal Sunshine of the Spotless Mind",
    "Year":"2004",
    "Rated":"R",
    "Released":"19 Mar 2004",
    "Runtime":"1 h 48 min",
    "Genre":"Drama, Romance, Sci-Fi",
    "Director":"Michel Gondry",
    "Writer":"Charlie Kaufman, Michel Gondry",
    "Actors":"Jim Carrey, Kate Winslet, Tom Wilkinson, Gerry Robert Byrne",
    "Plot":"A couple undergo a procedure to erase each other from their memories when their relationship turns sour, but it is only through the process of loss that they discover what they had to begin with.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"442,816",
    "imdbID":"tt0338013",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=lnSgSe2GzDc"
    }
  },
  {
    "Title":"Full Metal Jacket",
    "Year":"1987",
    "Rated":"R",
    "Released":"26 Jun 1987",
    "Runtime":"1 h 56 min",
    "Genre":"Drama, War",
    "Director":"Stanley Kubrick",
    "Writer":"Gustav Hasford, Stanley Kubrick",
    "Actors":"Matthew Modine, R. Lee Ermey, Vincent D'Onofrio, Adam Baldwin",
    "Plot":"A pragmatic U.S. Marine observes the dehumanizing effects the U.S.-Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDAzMjU3NzE0Nl5BMl5BanBnXkFtZTcwNTk1ODg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"310,666",
    "imdbID":"tt0093058",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=5IQqG0O8oQg"
    }
  },
  {
    "Title":"Oldboy",
    "Year":"2003",
    "Rated":"R",
    "Released":"21 Nov 2003",
    "Runtime":"2 h",
    "Genre":"Drama, Mystery, Thriller",
    "Director":"Chan-wook Park",
    "Writer":"Garon Tsuchiya, Nobuaki Minegishi",
    "Actors":"Min-sik Choi, Ji-tae Yu, Hye-jeong Kang, Dae-han Ji",
    "Plot":"After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"219,523",
    "imdbID":"tt0364569",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=ZrLcnrnEqyI"
    }
  },
  {
    "Title":"Braveheart",
    "Year":"1995",
    "Rated":"R",
    "Released":"24 May 1995",
    "Runtime":"2 h 57 min",
    "Genre":"Action, Biography, Drama, History, War",
    "Director":"Mel Gibson",
    "Writer":"Randall Wallace",
    "Actors":"Mel Gibson, Sophie Marceau, Patrick McGoohan, Angus Macfadyen",
    "Plot":"When his secret bride is executed for assaulting an English soldier who tried to rape her, a commoner begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron fist.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNjA4ODYxMDU3Nl5BMl5BanBnXkFtZTcwMzkzMTk3OA@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"483,156",
    "imdbID":"tt0112573",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=vbnGDeq40hI"
    }
  },
  {
    "Title":"L.A. Confidential",
    "Year":"1997",
    "Rated":"TV-MA",
    "Released":"19 Sep 1997",
    "Runtime":"2 h 18 min",
    "Genre":"Crime, Drama, Mystery, Thriller",
    "Director":"Curtis Hanson",
    "Writer":"James Ellroy, Brian Helgeland",
    "Actors":"Kevin Spacey, Russell Crowe, Guy Pearce, Kim Basinger",
    "Plot":"As corruption grows in 1950s LA, three policemen - the straight-laced, the brutal, and the sleazy - investigate a series of murders with their own brand of justice.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ5MTU4MzQ5NF5BMl5BanBnXkFtZTcwMjY1OTM2MQ@@._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"300,931",
    "imdbID":"tt0119488",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=C4XbnrmbEME"
    }
  },
  {
    "Title":"Bicycle Thieves",
    "Year":"1948",
    "Rated":"Not Rated",
    "Released":"13 Dec 1949",
    "Runtime":"1 h 33 min",
    "Genre":"Crime, Drama",
    "Director":"Vittorio De Sica",
    "Writer":"Luigi Bartolini, Cesare Zavattini",
    "Actors":"Lamberto Maggiorani, Enzo Staiola, Lianella Carell, Gino Saltamerenda",
    "Plot":"A man and his son search for a stolen bicycle vital for his job.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjA5MDY0NzM2M15BMl5BanBnXkFtZTcwNzI2NTA0MQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"57,797",
    "imdbID":"tt0040522",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=H3jnzXX9mXs"
    }
  },
  {
    "Title":"Chinatown",
    "Year":"1974",
    "Rated":"TV-14",
    "Released":"20 Jun 1974",
    "Runtime":"2 h 10 min",
    "Genre":"Crime, Drama, Mystery, Thriller",
    "Director":"Roman Polanski",
    "Writer":"Robert Towne",
    "Actors":"Jack Nicholson, Faye Dunaway, John Huston, Perry Lopez",
    "Plot":"A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption and murder.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTUyMTQ1NjA2OV5BMl5BanBnXkFtZTcwODQ1Njg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"148,870",
    "imdbID":"tt0071315",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=FueLhmwT8E4"
    }
  },
  {
    "Title":"Singin' in the Rain",
    "Year":"1952",
    "Rated":"G",
    "Released":"11 Apr 1952",
    "Runtime":"1 h 43 min",
    "Genre":"Comedy, Musical, Romance",
    "Director":"Stanley Donen, Gene Kelly",
    "Writer":"Adolph Green, Betty Comden",
    "Actors":"Gene Kelly, Donald O'Connor, Debbie Reynolds, Jean Hagen",
    "Plot":"A silent film production company and cast make a difficult transition to sound.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTUxMTIyNTI4Nl5BMl5BanBnXkFtZTcwNTk1ODQyMg@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"100,590",
    "imdbID":"tt0045152",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=36QiuRc_3I8"
    }
  },
  {
    "Title":"Princess Mononoke",
    "Year":"1997",
    "Rated":"PG-13",
    "Released":"26 Nov 1999",
    "Runtime":"2 h 14 min",
    "Genre":"Animation, Adventure, Fantasy",
    "Director":"Hayao Miyazaki",
    "Writer":"Hayao Miyazaki",
    "Actors":"Y\u00f4ji Matsuda, Yuriko Ishida, Y\u00fbko Tanaka, Billy Crudup",
    "Plot":"On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjgzNTUwODQzN15BMl5BanBnXkFtZTcwMTc4ODE3OQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"136,806",
    "imdbID":"tt0119698",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=pkWWWKKA8jY"
    }
  },
  {
    "Title":"Monty Python and the Holy Grail",
    "Year":"1975",
    "Rated":"PG",
    "Released":"25 May 1975",
    "Runtime":"1 h 31 min",
    "Genre":"Adventure, Comedy, Fantasy",
    "Director":"Terry Gilliam, Terry Jones",
    "Writer":"Graham Chapman, John Cleese",
    "Actors":"Graham Chapman, John Cleese, Eric Idle, Terry Gilliam",
    "Plot":"King Arthur and his knights embark on a low-budget search for the Grail, encountering many very silly obstacles.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTkzODczMTgwM15BMl5BanBnXkFtZTYwNTAwODI5._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"268,670",
    "imdbID":"tt0071853",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=RDM75-oXGmQ"
    }
  },
  {
    "Title":"The Lord of the Rings: The Return of the King",
    "Year":"2003",
    "Rated":"PG-13",
    "Released":"17 Dec 2003",
    "Runtime":"3 h 21 min",
    "Genre":"Action, Adventure, Fantasy",
    "Director":"Peter Jackson",
    "Writer":"J.R.R. Tolkien, Fran Walsh",
    "Actors":"Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom",
    "Plot":"Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjE4MjA1NTAyMV5BMl5BanBnXkFtZTcwNzM1NDQyMQ@@._V1_SX300.jpg",
    "imdbRating":"8.9",
    "imdbVotes":"767,958",
    "imdbID":"tt0167260",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=r5X-hFf6Bwo"
    }
  },
  {
    "Title":"Metropolis",
    "Year":"1927",
    "Rated":"Not Rated",
    "Released":"13 Mar 1927",
    "Runtime":"1 h 54 min",
    "Genre":"Drama, Sci-Fi",
    "Director":"Fritz Lang",
    "Writer":"Thea von Harbou, Thea von Harbou",
    "Actors":"Brigitte Helm, Alfred Abel, Gustav Fr\u00f6hlich, Rudolf Klein-Rogge",
    "Plot":"In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a working class prophet who predicts the coming of a savior to mediate their differences.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDAzNTkyODg1MF5BMl5BanBnXkFtZTgwMDA3NDkwMDE@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"75,994",
    "imdbID":"tt0017136",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=ZSExdX0tds4"
    }
  },
  {
    "Title":"Rashomon",
    "Year":"1950",
    "Rated":"Unrated",
    "Released":"26 Dec 1951",
    "Runtime":"1 h 28 min",
    "Genre":"Crime, Drama",
    "Director":"Akira Kurosawa",
    "Writer":"Ry\u00fbnosuke Akutagawa, Akira Kurosawa",
    "Actors":"Toshir\u00f4 Mifune, Machiko Ky\u00f4, Masayuki Mori, Takashi Shimura",
    "Plot":"A heinous crime and its aftermath are recalled from differing points of view.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjEzMzA4NDE2OF5BMl5BanBnXkFtZTcwNTc5MDI2NQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"69,263",
    "imdbID":"tt0042876",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=xCZ9TguVOIA"
    }
  },
  {
    "Title":"Some Like It Hot",
    "Year":"1959",
    "Rated":"Approved",
    "Released":"29 Mar 1959",
    "Runtime":"2 h",
    "Genre":"Comedy",
    "Director":"Billy Wilder",
    "Writer":"Billy Wilder, I.A.L. Diamond",
    "Actors":"Marilyn Monroe, Tony Curtis, Jack Lemmon, George Raft",
    "Plot":"When two musicians witness a mob hit, they flee the state in an all female band disguised as women, but further complications set in.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNzYzMDkzNDQ0N15BMl5BanBnXkFtZTcwNzQ0NDQyNA@@._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"120,784",
    "imdbID":"tt0053291",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=rI_lUHOCcbc"
    }
  },
  {
    "Title":"Amadeus",
    "Year":"1984",
    "Rated":"PG",
    "Released":"19 Sep 1984",
    "Runtime":"2 h 40 min",
    "Genre":"Biography, Drama, Music",
    "Director":"Milos Forman",
    "Writer":"Peter Shaffer, Peter Shaffer",
    "Actors":"F. Murray Abraham, Tom Hulce, Elizabeth Berridge, Roy Dotrice",
    "Plot":"The incredible story of Wolfgang Amadeus Mozart, told by his peer and secret rival Antonio Salieri - now confined to an insane asylum.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTg5NDkwMTk5N15BMl5BanBnXkFtZTYwODg3MDk2._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"183,901",
    "imdbID":"tt0086879",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=yIzhAKtEzY0"
    }
  },
  {
    "Title":"2001: A Space Odyssey",
    "Year":"1968",
    "Rated":"G",
    "Released":"11 Apr 1968",
    "Runtime":"2 h 40 min",
    "Genre":"Adventure, Mystery, Sci-Fi",
    "Director":"Stanley Kubrick",
    "Writer":"Stanley Kubrick, Arthur C. Clarke",
    "Actors":"Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter",
    "Plot":"Humanity finds a mysterious, obviously artificial, object buried beneath the Lunar surface and, with the intelligent computer H.A.L. 9000, sets off on a quest.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BNDYyMDgxNDQ5Nl5BMl5BanBnXkFtZTcwMjc1ODg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"278,502",
    "imdbID":"tt0062622",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=N6ywMnbef6Y"
    }
  },
  {
    "Title":"All About Eve",
    "Year":"1950",
    "Rated":"Approved",
    "Released":"15 Jan 1951",
    "Runtime":"2 h 18 min",
    "Genre":"Drama",
    "Director":"Joseph L. Mankiewicz",
    "Writer":"Joseph L. Mankiewicz",
    "Actors":"Bette Davis, Anne Baxter, George Sanders, Celeste Holm",
    "Plot":"An ingenue insinuates herself in to the company of an established but aging stage actress and her circle of theater friends.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjE4MDg3ODUzMF5BMl5BanBnXkFtZTcwODY1ODg3OA@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"57,605",
    "imdbID":"tt0042192",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=uHVYTPFgCqE"
    }
  },
  {
    "Title":"Witness for the Prosecution",
    "Year":"1957",
    "Rated":"Approved",
    "Released":"06 Feb 1958",
    "Runtime":"1 h 56 min",
    "Genre":"Drama, Mystery",
    "Director":"Billy Wilder",
    "Writer":"Agatha Christie, Billy Wilder",
    "Actors":"Tyrone Power, Marlene Dietrich, Charles Laughton, Elsa Lanchester",
    "Plot":"Agatha Christie tale of a man on trial for murder: a trial featuring surprise after surprise.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTc0MjgyNTUyNF5BMl5BanBnXkFtZTcwNDQzMDg0Nw@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"36,591",
    "imdbID":"tt0051201",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=KsVN1hv9D5c"
    }
  },
  {
    "Title":"The Sting",
    "Year":"1973",
    "Rated":"PG",
    "Released":"10 Jan 1974",
    "Runtime":"2 h 9 min",
    "Genre":"Comedy, Crime, Drama",
    "Director":"George Roy Hill",
    "Writer":"David S. Ward",
    "Actors":"Paul Newman, Robert Redford, Robert Shaw, Charles Durning",
    "Plot":"In 1930s Chicago, a young con man seeking revenge for his murdered partner teams up with a master of the big con to win a fortune from a criminal banker.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTY2OTM3Njk2MF5BMl5BanBnXkFtZTYwNzk4Njk4._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"118,638",
    "imdbID":"tt0070735",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=5-Fh2pMLFOM"
    }
  },
  {
    "Title":"The Apartment",
    "Year":"1960",
    "Rated":"Approved",
    "Released":"16 Sep 1960",
    "Runtime":"2 h 5 min",
    "Genre":"Comedy, Drama, Romance",
    "Director":"Billy Wilder",
    "Writer":"Billy Wilder, I.A.L. Diamond",
    "Actors":"Jack Lemmon, Shirley MacLaine, Fred MacMurray, Ray Walston",
    "Plot":"A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMTM1OTc4MzgzNl5BMl5BanBnXkFtZTcwNTE2NjgyMw@@._V1_SX300.jpg",
    "imdbRating":"8.3",
    "imdbVotes":"71,253",
    "imdbID":"tt0053604",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=B4OXm9-E8OQ"
    }
  },
  {
    "Title":"Grave of the Fireflies",
    "Year":"1988",
    "Rated":"Unrated",
    "Released":"16 Apr 1988",
    "Runtime":"1 h 29 min",
    "Genre":"Animation, Drama, War",
    "Director":"Isao Takahata",
    "Writer":"Akiyuki Nosaka, Isao Takahata",
    "Actors":"Tsutomu Tatsumi, Ayano Shiraishi, Akemi Yamaguchi, Yoshiko Shinohara",
    "Plot":"A tragic film covering a young boy and his little sister's struggle to survive in Japan during World War II.",
    "Poster":"http://ia.media-imdb.com/images/M/MV5BMjA0MzgwMTU4MV5BMl5BanBnXkFtZTcwODYxNjEzMQ@@._V1_SX300.jpg",
    "imdbRating":"8.4",
    "imdbVotes":"76,471",
    "imdbID":"tt0095327",
    "Type":"movie",
    "Response":"True",
    "Trailer":{
      "url":"https://www.youtube.com/watch?v=hxv9ghINEhs"
    }
  }
];